'use strict';
const $=id=>document.getElementById(id);
const states={pending:'宣告待確認',active:'已宣告',simulated:'模擬中',withdrawing:'撤回待確認',withdrawn:'已撤回',absent:'路由不存在',failed:'失敗'};
const actions={announce:'宣告',withdraw:'撤回',announce_pending:'宣告待確認',settings:'設定',recovered:'狀態恢復',absent:'路由不存在',withdrawn:'撤回確認'};
let settingsLoaded=false, controlState=null;
const fmt=(v,unit='')=>{if(!Number.isFinite(v))return '—';const units=['','K','M','G','T'];let n=0;while(Math.abs(v)>=1000&&n<4){v/=1000;n++}return `${v.toFixed(n?2:1)} ${units[n]}${unit}`.trim()};
const time=s=>!s||s.startsWith('0001-')?'尚無資料':new Date(s).toLocaleString('zh-TW',{hour12:false});
function message(s){$('message').textContent=s;$('message').hidden=!s}
async function api(path,method='GET',data){const res=await fetch(path,{method,headers:data===undefined?{}:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data),signal:AbortSignal.timeout(35000)});let body;try{body=await res.json()}catch{throw new Error(`HTTP ${res.status}`)}if(!res.ok)throw new Error(body.error||`HTTP ${res.status}`);return body}
function table(id,rows,empty='目前沒有資料'){const root=$(id);root.replaceChildren();if(!rows.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=10;td.textContent=empty;tr.append(td);root.append(tr);return}for(const cols of rows){const tr=document.createElement('tr');for(const value of cols){const td=document.createElement('td');if(value instanceof Node)td.append(value);else td.textContent=String(value??'—');tr.append(td)}root.append(tr)}}
function chart(id,history,key,unit){const canvas=$(id),ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height,left=78,right=w-12,top=22,bottom=h-26;ctx.clearRect(0,0,w,h);ctx.font='12px sans-serif';ctx.fillStyle='#526072';if(!history.length){ctx.fillText('等待流量統計…',left,90);return}const max=Math.max(1,...history.map(p=>p[key]));ctx.strokeStyle='#dce0e5';for(let i=0;i<3;i++){const y=top+(bottom-top)*i/2;ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(right,y);ctx.stroke();ctx.fillText(fmt(max*(1-i/2),unit),4,y+4)}const end=new Date(history.at(-1).time).getTime(),start=end-300000;ctx.strokeStyle='#1967b3';ctx.lineWidth=2;ctx.beginPath();history.forEach((p,i)=>{const x=left+(new Date(p.time).getTime()-start)/300000*(right-left),y=bottom-p[key]/max*(bottom-top);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle='#526072';ctx.fillText('5 分鐘前',left,h-6);ctx.fillText('現在',right-30,h-6)}
function verdictCell(value){const node=document.createElement('span');node.textContent=value;if(value==='非法（依清單）')node.className='invalid';return node}
function renderTraffic(t){$('bps').textContent=fmt(t.current.bps,'bps');$('pps').textContent=fmt(t.current.pps,'pps');$('samples').textContent=fmt(t.current.samples,'/s');$('lastFlow').textContent=time(t.last_flow);$('overflow').hidden=!t.overflow;$('overflow').textContent=`目的網段表已略過 ${t.overflow} 筆超出容量的樣本；總量仍有計入。`;for(const key of ['destinations','protocols'])table(key,t[key].map(r=>[r.name,fmt(r.bps,'bps'),fmt(r.pps)]));
 table('flags',t.flags.map(r=>[r.combination,verdictCell(r.verdict),r.phase,r.bps.toFixed(3)+' bps',r.pps.toFixed(0)+' pps']),'尚無 sFlow TCP 封包取樣；NetFlow 資料請看下表');
 table('flowFlags',(t.flow_flags||[]).map(r=>[r.combination,r.source,r.rule_match==='allowed'?'符合清單':r.rule_match==='unlisted'?'未列入清單':'資料不足',r.verdict,r.bps.toFixed(3)+' bps',r.pps.toFixed(0)+' pps']),'尚無 NetFlow/IPFIX TCP 累積資料');
 chart('bandwidth',t.history,'bps','bps');chart('packets',t.history,'pps','pps')}
function renderControl(s){controlState=s;const live=s.config.mode==='live';$('bgpStatus').textContent=live?(s.bgp.connected?`已連線 · AS${s.bgp.asn} · Router ID ${s.bgp.router_id}`:`未連線 · ${s.bgp.error||'檢查中'}`):'模擬模式，未連接 GoBGP';$('modeNotice').textContent=live?'實際模式：宣告與撤回會送至 GoBGP。':'模擬模式：可測試操作流程，不會發送路由。';$('announce').textContent=live?'宣告路由':'模擬宣告';table('peers',(s.bgp.peers||[]).map(p=>[p.address,p.asn,p.state]),live?'尚無鄰居':'模擬模式');
 if(!settingsLoaded){const f=$('settingsForm');f.elements.mode.value=s.config.mode;f.elements.endpoint.value=s.config.endpoint;f.elements.allowed_prefixes.value=s.config.allowed_prefixes.join('\n');settingsLoaded=true}
 table('routes',[...s.routes].reverse().map(r=>{let action='—';if(!['withdrawn','absent','failed'].includes(r.state)){action=document.createElement('button');action.textContent='撤回';action.addEventListener('click',()=>perform(action,()=>api(`/api/routes/${r.id}/withdraw`,'POST',{}),'撤回操作已送出'))}return [r.prefix,r.next_hop,r.communities.join(', '),r.mode==='live'?'實際':'模擬',states[r.state]||r.state,time(r.expires),[r.note,r.error].filter(Boolean).join('／'),action]}),'尚無路由操作');
 table('events',[...s.events].reverse().map(e=>[time(e.time),actions[e.action]||e.action,e.prefix||'—',e.mode==='live'?'實際':'模擬',e.detail]),'尚無操作紀錄');if(s.persistence_error)message('狀態儲存失敗：'+s.persistence_error)
}
async function perform(button,fn,success){button.disabled=true;try{await fn();message(success);renderControl(await api('/api/state'))}catch(e){message(e.message)}finally{button.disabled=false}}
$('routeForm').addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget;perform($('announce'),()=>api('/api/routes','POST',{prefix:f.elements.prefix.value.trim(),next_hop:f.elements.next_hop.value.trim(),communities:f.elements.communities.value.split(/[\s,]+/).filter(Boolean),ttl:Number(f.elements.ttl.value),note:f.elements.note.value.trim()}),'路由操作已完成')});
$('settingsForm').addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget;perform(f.querySelector('button'),()=>api('/api/settings','PUT',{mode:f.elements.mode.value,endpoint:f.elements.endpoint.value.trim(),allowed_prefixes:f.elements.allowed_prefixes.value.split(/[\s,]+/).filter(Boolean)}),'設定已儲存')});
const grafana=new URL(location.href);grafana.port='3000';grafana.pathname='/d/aegisflow-overview';grafana.search='';grafana.hash='';$('grafana').href=grafana.href;
async function pollTraffic(){try{renderTraffic(await api('/api/traffic'));$('connection').textContent='流量連線正常 · '+new Date().toLocaleTimeString('zh-TW')}catch(e){$('connection').textContent='流量更新失敗：'+e.message}finally{setTimeout(pollTraffic,1000)}}
async function pollControl(){try{renderControl(await api('/api/state'))}catch(e){$('bgpStatus').textContent='控制狀態更新失敗：'+e.message}finally{setTimeout(pollControl,3000)}}
async function loadFlagRules(){try{const rules=await api('/api/tcp-flag-rules');table('flagRules',rules.map(r=>[r.combination,r.phase,r.description]))}catch(e){table('flagRules',[],'規則載入失敗：'+e.message);setTimeout(loadFlagRules,5000)}}
loadFlagRules();pollTraffic();pollControl();
