'use strict';
const rulePhases={warming:'視窗準備中',watching:'監控中',holding:'持續超標',pending:'處理中',active:'已宣告',recovering:'等待復原',cooldown:'冷卻中',stale:'資料中斷',disabled:'停用',error:'操作失敗',disconnected:'尚未連線'};
let ruleViews=[],editingRule=null,ruleCommunities=[];
const rulePreviewValues=new Map();
const rf=$('ruleForm');
const whole=v=>Number.isFinite(v)?Math.ceil(v).toLocaleString('en-US'):'—';
const sizeBucketText=n=>n===65600?'≥65600 Bytes':n+'–<'+(n+100)+' Bytes';
const ruleUnit=metric=>metric==='packets'?'包／視窗':metric;
for(let n=0;n<=65600;n+=100)rf.elements.mean_packet_size_bucket.add(new Option(sizeBucketText(n),n));
function renderCommunityCards(){const cards=$('ruleCommunityCards');cards.replaceChildren();for(const value of ruleCommunities){const card=document.createElement('span');card.className='community-card';const text=document.createElement('span');text.textContent=value;const remove=ruleButton('×',()=>{ruleCommunities=ruleCommunities.filter(v=>v!==value);renderCommunityCards()});remove.setAttribute('aria-label','移除 '+value);card.append(text,remove);cards.append(card)}}
function addCommunities(){const input=$('ruleCommunityInput'),values=input.value.trim().split(/[\s,，]+/).filter(Boolean);const normalized=[];for(const value of values){const parts=value.split(':');const max=parts.length===2?65535:4294967295;if(![2,3].includes(parts.length)||parts.some(v=>!/^\d+$/.test(v)||Number(v)>max)){ $('ruleCommunityError').textContent='Community 格式錯誤：'+value;input.focus();return false}normalized.push(parts.map(Number).join(':'))}const next=[...new Set([...ruleCommunities,...normalized])];if(next.length>16){$('ruleCommunityError').textContent='最多 16 組 Community';return false}ruleCommunities=next;input.value='';$('ruleCommunityError').textContent='';renderCommunityCards();return true}
function updateRuleProtocol(){const tcp=rf.elements.protocol.value==='tcp';$('ruleFlagsLabel').hidden=!tcp;if(!tcp)rf.elements.tcp_flags.value=''}
function editRule(r){editingRule=r.id;rf.elements.id.value=r.id;for(const key of ['name','direction','protocol','destination','metric','threshold','window_seconds','hold_seconds','recovery_threshold','recovery_seconds','cooldown_seconds'])rf.elements[key].value=r[key];rf.elements.mean_packet_size_bucket.value=r.mean_packet_size_bucket==null?'':String(r.mean_packet_size_bucket);rf.elements.tcp_flags.value=r.tcp_flags==null?'':String(r.tcp_flags);updateRuleProtocol();rf.elements.enabled.checked=r.enabled;for(const key of ['prefix','next_hop','ttl'])rf.elements[key].value=r.route[key];ruleCommunities=[...r.route.communities];$('ruleCommunityInput').value='';$('ruleCommunityError').textContent='';renderCommunityCards();$('ruleEditorTitle').textContent='編輯規則：'+r.name;$('ruleEditor').open=true;$('ruleEditor').scrollIntoView({behavior:'smooth',block:'start'})}
function resetRule(){rf.reset();editingRule=null;rf.elements.id.value='';ruleCommunities=[];renderCommunityCards();$('ruleCommunityError').textContent='';$('ruleAdvanced').open=false;updateRuleProtocol();$('ruleEditorTitle').textContent='新增規則'}
function ruleButton(label,fn){const b=document.createElement('button');b.type='button';b.textContent=label;b.addEventListener('click',()=>fn(b));return b}
async function ruleAction(button,fn){button.disabled=true;try{await fn();await refreshRules()}catch(e){$('ruleResult').textContent=e.message}finally{button.disabled=false}}
function renderRules(data){ruleViews=data.rules;for(const id of rulePreviewValues.keys())if(!data.rules.some(r=>r.id===id))rulePreviewValues.delete(id);table('ruleRows',data.rules.map(r=>{const actions=document.createElement('div');actions.append(ruleButton(r.enabled?'停用並撤回':'啟用',b=>ruleAction(b,()=>api(`/api/rules/${r.id}/enabled`,'POST',{enabled:!r.enabled}))),ruleButton('編輯',()=>editRule(r)),ruleButton('刪除',b=>ruleAction(b,()=>api(`/api/rules/${r.id}`,'DELETE',{}))));const input=document.createElement('input');input.type='number';input.min='0';input.step='any';input.value=rulePreviewValues.get(r.id)??r.threshold;input.addEventListener('input',()=>rulePreviewValues.set(r.id,input.value));input.setAttribute('aria-label',r.name+'試算數值');input.className='rule-preview';actions.append(input,ruleButton('試算',b=>ruleAction(b,async()=>{const value=Number(input.value);if(!input.value||!Number.isFinite(value)||value<0)throw Error('請填入有效的試算數值');const result=await api(`/api/rules/${r.id}/preview`,'POST',{value});$('ruleResult').textContent=r.name+'：'+(result.matched?'達到門檻':'未達門檻')})));return [r.name,r.destination+' / '+r.protocol+' / '+r.direction+(r.mean_packet_size_bucket==null?'':' / 平均包長 '+sizeBucketText(r.mean_packet_size_bucket))+(r.tcp_flags==null?'':' / '+(rf.elements.tcp_flags.querySelector(`option[value="${r.tcp_flags}"]`)?.textContent||r.tcp_flags)),whole(r.threshold)+' '+ruleUnit(r.metric)+'，持續 '+r.hold_seconds+' 秒',whole(r.runtime.value)+' '+ruleUnit(r.metric)+' / '+(rulePhases[r.runtime.phase]||r.runtime.phase)+(r.runtime.error?' / '+r.runtime.error:''),r.route.prefix+' / '+r.route.communities.join(', '),actions]}),'尚無規則');$('ruleStatus').textContent=data.rules.length+' 條規則'+(data.dropped?'；判斷佇列略過 '+data.dropped+' 筆，正在重建視窗':'')+(data.persistence_error?'；儲存失敗：'+data.persistence_error:'')}
async function refreshRules(){renderRules(await api('/api/rules'))}
async function pollRules(){try{await refreshRules()}catch(e){$('ruleStatus').textContent='規則讀取失敗：'+e.message}finally{setTimeout(pollRules,1000)}}
rf.addEventListener('submit',e=>{e.preventDefault();if(!addCommunities())return;if(!ruleCommunities.length){$('ruleCommunityError').textContent='請新增至少一組 Community';$('ruleCommunityInput').focus();return}const f=rf.elements;const rule={name:f.name.value,enabled:f.enabled.checked,source:'netflow9',interface_key:'netflow9@172.30.10.1@15',direction:f.direction.value,protocol:f.protocol.value,destination:f.destination.value,tcp_flags:f.tcp_flags.value===''?null:Number(f.tcp_flags.value),mean_packet_size_bucket:f.mean_packet_size_bucket.value===''?null:Number(f.mean_packet_size_bucket.value),metric:f.metric.value,threshold:Number(f.threshold.value),window_seconds:Number(f.window_seconds.value),hold_seconds:Number(f.hold_seconds.value),recovery_threshold:Number(f.recovery_threshold.value),recovery_seconds:Number(f.recovery_seconds.value),cooldown_seconds:Number(f.cooldown_seconds.value),route:{prefix:f.prefix.value,next_hop:f.next_hop.value,communities:[...ruleCommunities],ttl:Number(f.ttl.value),note:''}};ruleAction(rf.querySelector('[type=submit]'),async()=>{await api(editingRule?`/api/rules/${editingRule}`:'/api/rules',editingRule?'PUT':'POST',rule);$('ruleResult').textContent='規則已儲存';resetRule()})});
$('ruleNew').addEventListener('click',resetRule);rf.elements.protocol.addEventListener('change',updateRuleProtocol);
$('ruleCommunityInput').addEventListener('keydown',e=>{if(e.isComposing)return;if(e.key==='Enter'){e.preventDefault();addCommunities()}else if(e.key==='Backspace'&&e.currentTarget.value===''){e.preventDefault();if(!e.repeat){ruleCommunities.pop();renderCommunityCards();$('ruleCommunityError').textContent=''}}});
rf.addEventListener('invalid',e=>{if($('ruleAdvanced').contains(e.target))$('ruleAdvanced').open=true},true);
async function loadRuleMetadata(){try{const flags=await api('/api/tcp-flag-rules');const selected=rf.elements.tcp_flags.value;rf.elements.tcp_flags.replaceChildren(new Option('全部組合',''));for(const r of flags)rf.elements.tcp_flags.add(new Option(r.combination,r.mask));rf.elements.tcp_flags.value=selected}catch{}finally{setTimeout(loadRuleMetadata,10000)}}
loadRuleMetadata();pollRules();
