'use strict';
const rulePhases={warming:'視窗準備中',watching:'監控中',holding:'持續超標',pending:'處理中',active:'已宣告',recovering:'等待復原',cooldown:'冷卻中',stale:'資料中斷',disabled:'停用',error:'操作失敗',disconnected:'尚未連線'};
let ruleViews=[],ruleInterfaces=[],editingRule=null;
const rulePreviewValues=new Map();
const rf=$('ruleForm');
const whole=v=>Number.isFinite(v)?Math.ceil(v).toLocaleString('en-US'):'—';
function ruleInterfaceOptions(){const select=rf.elements.interface_key,current=select.value;select.replaceChildren(new Option('請選擇介面',''));for(const row of ruleInterfaces.filter(r=>r.source===rf.elements.source.value)){select.add(new Option(row.exporter+' / '+(row.index==='0'?'未知介面':row.index),row.key))}if(current&&!Array.from(select.options).some(o=>o.value===current))select.add(new Option(current+'（目前未回報）',current));select.value=current||((rf.elements.source.value==='netflow9'&&Array.from(select.options).some(o=>o.value==='netflow9@172.30.10.1@15'))?'netflow9@172.30.10.1@15':'')}
function editRule(r){editingRule=r.id;rf.elements.id.value=r.id;for(const key of ['name','source','direction','protocol','destination','metric','threshold','window_seconds','hold_seconds','recovery_threshold','recovery_seconds','cooldown_seconds'])rf.elements[key].value=r[key];ruleInterfaceOptions();if(r.interface_key&&!Array.from(rf.elements.interface_key.options).some(o=>o.value===r.interface_key))rf.elements.interface_key.add(new Option(r.interface_key,r.interface_key));rf.elements.interface_key.value=r.interface_key;rf.elements.tcp_flags.value=r.tcp_flags==null?'':String(r.tcp_flags);rf.elements.enabled.checked=r.enabled;for(const key of ['prefix','next_hop','ttl'])rf.elements[key].value=r.route[key];rf.elements.communities.value=r.route.communities.join(', ');$('ruleEditorTitle').textContent='編輯規則：'+r.name;$('ruleEditor').open=true;$('ruleEditor').scrollIntoView({behavior:'smooth',block:'start'})}
function resetRule(){rf.reset();editingRule=null;rf.elements.id.value='';$('ruleEditorTitle').textContent='新增規則';ruleInterfaceOptions()}
function ruleButton(label,fn){const b=document.createElement('button');b.type='button';b.textContent=label;b.addEventListener('click',()=>fn(b));return b}
async function ruleAction(button,fn){button.disabled=true;try{await fn();await refreshRules()}catch(e){$('ruleResult').textContent=e.message}finally{button.disabled=false}}
function renderRules(data){ruleViews=data.rules;for(const id of rulePreviewValues.keys())if(!data.rules.some(r=>r.id===id))rulePreviewValues.delete(id);table('ruleRows',data.rules.map(r=>{const actions=document.createElement('div');actions.append(ruleButton(r.enabled?'停用並撤回':'啟用',b=>ruleAction(b,()=>api(`/api/rules/${r.id}/enabled`,'POST',{enabled:!r.enabled}))),ruleButton('編輯',()=>editRule(r)),ruleButton('刪除',b=>ruleAction(b,()=>api(`/api/rules/${r.id}`,'DELETE',{}))));const input=document.createElement('input');input.type='number';input.min='0';input.step='any';input.value=rulePreviewValues.get(r.id)??r.threshold;input.addEventListener('input',()=>rulePreviewValues.set(r.id,input.value));input.setAttribute('aria-label',r.name+'試算數值');input.className='rule-preview';actions.append(input,ruleButton('試算',b=>ruleAction(b,async()=>{const value=Number(input.value);if(!input.value||!Number.isFinite(value)||value<0)throw Error('請填入有效的試算數值');const result=await api(`/api/rules/${r.id}/preview`,'POST',{value});$('ruleResult').textContent=r.name+'：'+(result.matched?'達到門檻':'未達門檻')+'。'+result.message})));return [r.name,r.destination+' / '+r.protocol+' / '+r.direction+' / '+(r.interface_key||r.source+' 所有介面')+(r.tcp_flags==null?'':' / '+(rf.elements.tcp_flags.querySelector(`option[value="${r.tcp_flags}"]`)?.textContent||r.tcp_flags)),whole(r.threshold)+' '+r.metric+'，持續 '+r.hold_seconds+' 秒',whole(r.runtime.value)+' '+r.metric+' / '+(rulePhases[r.runtime.phase]||r.runtime.phase)+(r.runtime.error?' / '+r.runtime.error:''),r.route.prefix+' / '+r.route.communities.join(', '),actions]}),'尚無規則');$('ruleStatus').textContent=data.rules.length+' 條規則'+(data.dropped?'；判斷佇列略過 '+data.dropped+' 筆，正在重建視窗':'')+(data.persistence_error?'；儲存失敗：'+data.persistence_error:'')}
async function refreshRules(){renderRules(await api('/api/rules'))}
async function pollRules(){try{await refreshRules()}catch(e){$('ruleStatus').textContent='規則讀取失敗：'+e.message}finally{setTimeout(pollRules,1000)}}
rf.addEventListener('submit',e=>{e.preventDefault();const f=rf.elements;const rule={name:f.name.value,enabled:f.enabled.checked,source:f.source.value,interface_key:f.interface_key.value,direction:f.direction.value,protocol:f.protocol.value,destination:f.destination.value,tcp_flags:f.tcp_flags.value===''?null:Number(f.tcp_flags.value),metric:f.metric.value,threshold:Number(f.threshold.value),window_seconds:Number(f.window_seconds.value),hold_seconds:Number(f.hold_seconds.value),recovery_threshold:Number(f.recovery_threshold.value),recovery_seconds:Number(f.recovery_seconds.value),cooldown_seconds:Number(f.cooldown_seconds.value),route:{prefix:f.prefix.value,next_hop:f.next_hop.value,communities:f.communities.value.split(/[\s,]+/).filter(Boolean),ttl:Number(f.ttl.value),note:''}};ruleAction(rf.querySelector('[type=submit]'),async()=>{await api(editingRule?`/api/rules/${editingRule}`:'/api/rules',editingRule?'PUT':'POST',rule);$('ruleResult').textContent='規則已儲存';resetRule()})});
$('ruleNew').addEventListener('click',resetRule);rf.elements.source.addEventListener('change',()=>{rf.elements.interface_key.value='';ruleInterfaceOptions()});rf.elements.protocol.addEventListener('change',()=>{if(rf.elements.protocol.value!=='tcp')rf.elements.tcp_flags.value=''});
async function loadRuleMetadata(){try{ruleInterfaces=await api('/api/interfaces');ruleInterfaceOptions();const flags=await api('/api/tcp-flag-rules');const selected=rf.elements.tcp_flags.value;rf.elements.tcp_flags.replaceChildren(new Option('全部組合',''));for(const r of flags)rf.elements.tcp_flags.add(new Option(r.combination,r.mask));rf.elements.tcp_flags.value=selected}catch{}finally{setTimeout(loadRuleMetadata,10000)}}
loadRuleMetadata();pollRules();
